Decode E-mail Bodys if they are Base64 encoded
gophish/gophish pull request #1938
Opened 2020-08-17 16:20 UTC by supermopf

Some Email-Bodys are base64 encoded, when they are send as an attachment in an Outlook/Exchange Environment.

This checks if the body is decodable and decodes it if needed.

2020-08-19 04:08 UTC, jordan-wright commented on imap/monitor.go
> +	if(IsBase64(emailContent)){
What is `IsBase64`?

2020-08-19 04:09 UTC, jordan-wright requested changes
Hi there,

I think `IsBase64` is missing. Additionally, I'd ask that you please run `goimports` on the file to ensure consistent formatting.

2020-08-19 07:18 UTC, supermopf commented
Hey, in my excitement I totally forgot to add the function in the code. See the latest commit for your requested changes :)

2020-08-20 03:51 UTC, jordan-wright commented
Can you provide an example email where this occurs? I believe this should be handled already by looking at the `Content-Transfer-Encoding` header of the particular section, but would love to see a counter-example.

I'm just thinking of more robust ways we could handle this, since just trying to base64 decode and operating on the error feels like it could cause issues.

2020-08-20 08:27 UTC, supermopf commented
Yes, there should be a better way to implement it, it was just the quick way, that fixed the problem in our environment.

So what i did to generate the mail:

1. Open new Email
2. Attach GoPhish Email
3. Send to Mailbox

To see what happens, I modified the checkRIDS Function to the following:
```
func checkRIDs(em *email.Email, rids map[string]bool) {
	// Check Text and HTML
	emailContent := string(em.Text) + string(em.HTML)

	log.Info("Email Headers:", em.Headers)
	log.Info("Email Text:", string(em.Text))
	log.Info("Email HTML:", string(em.HTML))

	for _, r := range goPhishRegex.FindAllStringSubmatch(emailContent, -1) {
		newrid := r[len(r)-1]
		if !rids[newrid] {
			rids[newrid] = true
		}
	}
}
```

Now the Log reads the following:

```
time="2020-08-20T10:09:05+02:00" level=info msg="Email Headers:map[Accept-Language:[de-DE, en-US] Content-Language:[de-DE] Content-Type:[multipart/mixed; boundary=\"_002_2c72691820064bcaac2c73b417d55f32cbrde_\"] Date:[Thu, 20 Aug 2020 10:07:33 +0200] Message-Id:[<2c72691820064bcaac2c73b417d55f32@cbr.de>] Mime-Version:[1.0] Received:[from KH-EXCH-MBX02.cbr.de (10.60.1.12) by KH-EXCH-MBX01.cbr.de (10.60.1.11) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1913.5 via Mailbox Transport; Thu, 20 Aug 2020 10:07:34 +0200 from KH-EXCH-MBX01.cbr.de (10.60.1.11) by KH-EXCH-MBX02.cbr.de (10.60.1.12) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1913.5; Thu, 20 Aug 2020 10:07:34 +0200 from KH-EXCH-MBX01.cbr.de ([fe80::b46b:c039:b638:cb53]) by KH-EXCH-MBX01.cbr.de ([fe80::b46b:c039:b638:cb53%12]) with mapi id 15.01.1913.007; Thu, 20 Aug 2020 10:07:33 +0200] Thread-Index:[AdZ2yPSvdNL/neRGRRO2uky0Z/cwNw==] Thread-Topic:[Check this mail] X-Ms-Exchange-Organization-Authas:[Internal] X-Ms-Exchange-Organization-Authmechanism:[04] X-Ms-Exchange-Organization-Authsource:[KH-EXCH-MBX01.cbr.de] X-Ms-Exchange-Organization-Network-Message-Id:[559f7375-31b3-42f4-378e-08d844e017f3] X-Ms-Exchange-Organization-Recordreviewcfmtype:[0] X-Ms-Exchange-Organization-Scl:[-1] X-Ms-Has-Attach:[yes] X-Ms-Tnef-Correlator:[]]"
time="2020-08-20T10:09:05+02:00" level=info msg="Email Text:"
time="2020-08-20T10:09:05+02:00" level=info msg="Email HTML:<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" xmlns:m=\"http://schemas.microsoft.com/office/2004/12/omml\" xmlns=\"http://www.w3.org/TR/REC-html40\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=us-ascii\">\n<meta name=\"Generator\" content=\"Microsoft Word 15 (filtered medium)\">\n<style><!--\n/* Font Definitions */\n@font-face\n\t{font-family:\"Cambria Math\";\n\tpanose-1:2 4 5 3 5 4 6 3 2 4;}\n@font-face\n\t{font-family:Calibri;\n\tpanose-1:2 15 5 2 2 2 4 3 2 4;}\n/* Style Definitions */\np.MsoNormal, li.MsoNormal, div.MsoNormal\n\t{margin:0cm;\n\tmargin-bottom:.0001pt;\n\tfont-size:11.0pt;\n\tfont-family:\"Calibri\",sans-serif;\n\tmso-fareast-language:EN-US;}\n.MsoChpDefault\n\t{mso-style-type:export-only;\n\tfont-family:\"Calibri\",sans-serif;\n\tmso-fareast-language:EN-US;}\n@page WordSection1\n\t{size:612.0pt 792.0pt;\n\tmargin:70.85pt 70.85pt 2.0cm 70.85pt;}\ndiv.WordSection1\n\t{page:WordSection1;}\n--></style><!--[if gte mso 9]><xml>\n<o:shapedefaults v:ext=\"edit\" spidmax=\"1026\" />\n</xml><![endif]--><!--[if gte mso 9]><xml>\n<o:shapelayout v:ext=\"edit\">\n<o:idmap v:ext=\"edit\" data=\"1\" />\n</o:shapelayout></xml><![endif]-->\n</head>\n<body lang=\"DE\" link=\"#0563C1\" vlink=\"#954F72\">\n<div class=\"WordSection1\">\n<p class=\"MsoNormal\"><o:p>&nbsp;</o:p></p>\n</div>\n</body>\n</html>\n"
time="2020-08-20T10:09:05+02:00" level=info msg="Detected Content-Typemessage/rfc822"
time="2020-08-20T10:09:05+02:00" level=info msg="Email Headers:map[Content-Id:[<C5A5657043B5E64F9390C8DD8B1FC438@cbr.de>] Content-Language:[de-DE] Content-Transfer-Encoding:[base64] Content-Type:[text/html; charset=\"utf-8\"] Date:[Thu, 20 Aug 2020 10:04:13 +0200] Message-Id:[<1597910653994958800.940.8397135838471980185@KH-GOLDPHISH01>] Mime-Version:[1.0] Received:[from KH-EXCH-MBX02.cbr.de (10.60.1.12) by KH-EXCH-MBX01.cbr.de (10.60.1.11) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1913.5 via Mailbox Transport; Thu, 20 Aug 2020 10:04:14 +0200 from KH-EXCH-CAS01.cbr.de (10.60.1.13) by KH-EXCH-MBX02.cbr.de (10.60.1.12) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1913.5; Thu, 20 Aug 2020 10:04:14 +0200 from KH-GOLDPHISH01 (10.0.7.200) by mail.cbr.de (10.60.1.13) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256) id 15.1.1913.5 via Frontend Transport; Thu, 20 Aug 2020 10:04:14 +0200] Thread-Index:[AQHWdsh+MfhEd/EpWUa4Uy+ndNcxIw==] Thread-Topic:[Test-base64] X-Mailer:[gophish] X-Ms-Exchange-Messagesentrepresentingtype:[1] X-Ms-Exchange-Organization-Authmechanism:[10] X-Ms-Exchange-Organization-Authsource:[KH-EXCH-CAS01.cbr.de] X-Ms-Exchange-Organization-Network-Message-Id:[628573d1-b2e5-408d-74b8-08d844dfa0f0] X-Ms-Exchange-Organization-Recordreviewcfmtype:[0] X-Ms-Has-Attach:[] X-Ms-Tnef-Correlator:[]]"
time="2020-08-20T10:09:05+02:00" level=info msg="Email Text:"
time="2020-08-20T10:09:05+02:00" level=info msg="Email HTML:PGh0bWw+DQo8aGVhZD4NCjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0i\ndGV4dC9odG1sOyBjaGFyc2V0PXV0Zi04Ij4NCjx0aXRsZT48L3RpdGxlPg0KPC9oZWFkPg0KPGJv\nZHk+DQo8ZGl2IHN0eWxlPSJib3JkZXI6bm9uZTtib3JkZXItbGVmdDpzb2xpZCAjRkZDQjAwIDYu\nMHB0O3BhZGRpbmc6MGNtIDBjbSAwY20gMi4wcHQ7bWFyZ2luLWJvdHRvbToyMHB4OyI+DQo8cCBz\ndHlsZT0ibWFyZ2luOjBjbTttYXJnaW4tYm90dG9tOi4wMDAxcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5\nO2xpbmUtaGVpZ2h0OjEyLjBwdDtiYWNrZ3JvdW5kOiNGRkY0Q0QiPg0KPHNwYW4gc3R5bGU9ImZv\nbnQtc2l6ZToxMC4wcHQ7Y29sb3I6IzY1NUUyQyI+VGhpcyBlbWFpbCB3YXMgc2VudCBmcm9tIG91\ndHNpZGUgb2YgdGhlIG9yZ2FuaXNhdGlvbi48YnI+DQpQbGVhc2UgZG8gbm90IGNsaWNrIG9uIGxp\nbmtzIG9yIG9wZW4gYXR0YWNobWVudHMgdW5sZXNzIHlvdSBhcmUgc3VyZSwgdGhhdCB0aGUgc2Vu\nZGVyIGFuZCBjb250ZW50IGlzIHNhZmUuPC9zcGFuPg0KPC9wPg0KPC9kaXY+DQo8ZGl2Pg0KPHA+\naHR0cHM6Ly9teS1waGlzaGluZy11cmwuY29tP3JpZD1sU0tDYkhuPC9wPg0KPGltZyBhbHQ9IiIg\nc3R5bGU9ImRpc3BsYXk6IG5vbmUiIHNyYz0iaHR0cHM6Ly9teS1waGlzaGluZy11cmwuY29tL3Ry\nYWNrP3JpZD1sU0tDYkhuIj4NCjwvZGl2Pg0KPC9ib2R5Pg0KPC9odG1sPg0K\n"
time="2020-08-20T10:09:05+02:00" level=info msg="User '\"Lange, Victor\" <victor.lange@cbr.de>' reported email with subject 'Check this mail'. This is not a GoPhish campaign; you should investigate it."
```

You can see that the  `Content-Transfer-Encoding`  Header is set to [base64] in the attachment mail. But somehow the HTML or Text Property just outputs base64.

Also important: The base 64 in the output is interrupted by newline characters `\n` which could lead to problems.

The detection of our phishing url fails, because the the text is still in base64. 

Maybe its a bug in your email libary https://github.com/jordan-wright/email

I've attached a sample mail for more investigation.
[test-base64.zip](https://github.com/gophish/gophish/files/5101709/test-base64.zip)


Have a nice day!

2020-08-24 18:25 UTC, jordan-wright commented
Hey @supermopf,

I don't think I can reproduce the issue with the email you provided. The `.msg` appears to be in some kind of Outlook-specific binary format. Could you please attach a plaintext version of the raw email?

2020-08-25 09:33 UTC, supermopf commented
Hey @jordan-wright ,

since Outlook wont give me any option to export the "raw" mail, I used thunderbird to get the raw mail. (Since it should not matter, because we're accesing over IMAP with GoPhish)

I've uploaded the file to pastebin:

https://pastebin.com/gnx0YaLg

2020-11-25 09:24 UTC, supermopf commented
Hey,

this issue is fixed with version v0.11.0

Have a nice day,
Victor

2020-11-25 09:24 UTC, closed without merging