Added functionality to lock accounts (+bug fix)
gophish/gophish pull request #2060
Opened 2020-12-05 21:32 UTC by glennzw

A little update that's been useful for me, so maybe it'll be useful for y'all too. This pull request adds functionality to lock accounts:

Create new user or edit existing user:
<img width="400" alt="newuser" src="https://user-images.githubusercontent.com/3966613/101265669-92808000-3748-11eb-85a0-d8baaff2a36d.png">

Result when logging in with the correct password whilst account is locked:
<img width="320" alt="locked" src="https://user-images.githubusercontent.com/3966613/101265675-96ac9d80-3748-11eb-9227-625d501ea9f1.png">

I also fixed a bug whereby the "Require the user to set a new password" was not being saved to the database when creating new users (it only works when editing an existing user). I'm surprised we hadn't noticed this one yet 😅

I also tweaked the UI such that when you edit a user the "Require the user to set a new password" status is set in the modal from the database (so you know if they'e changed it).

2020-12-06 19:43 UTC, jordan-wright requested changes
This largely LGTM. I added a note about a small typo. One thing I'd ask is if we could add a test to make sure this works as intended. I believe you can find inspiration in `route_test.go`, and it should be a matter of making a new test with the same `setupTest()`, then modifying the user to be locked, then maybe just checking if our message appears in the resulting HTML.

2020-12-06 19:43 UTC, jordan-wright commented on controllers/route.go
> +			as.handleInvalidLogin(w, r, "Acount Locked")
```suggestion
			as.handleInvalidLogin(w, r, "Account Locked")
```

Small typo

2020-12-07 13:55 UTC, glennzw commented on controllers/route.go
> +			as.handleInvalidLogin(w, r, "Acount Locked")
Good eyes, my bad.

2020-12-07 14:00 UTC, glennzw commented
Thanks @jordan-wright ! Ah good  point on the test case, I must remember to include these. I've added logic to add a second user with a locked account and  a new test case `TestAccountLocked()`:


```
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s -run ^TestAccountLocked$ github.com/gophish/gophish/controllers

ok  	github.com/gophish/gophish/controllers	0.287s
```

2020-12-07 14:56 UTC, merged

2020-12-07 14:56 UTC, jordan-wright commented
LGTM! Thanks @glennzw!

2020-12-07 18:17 UTC, glennzw commented
Cool!

I noticed the minified `users.min.js` wasn't updated in the merge though.